export default {
    LOGIN_POST_REQUEST: 'POST_LOGIN_REQUEST',
    LOGIN_POST_SUCCESS: 'POST_LOGIN_SUCCESS',
    LOGIN_POST_ERROR: 'POST_LOGIN_ERROR',

    SET_LOGIN_CRED: 'SET_LOGIN_CRED',
    FLUSH_LOGIN_CRED: 'FLUSH_LOGIN_CRED',

    GET_FORM_REQUEST: 'GET_FORM_REQUEST',
    GET_FORM_SUCCESS: 'GET_FORM_SUCCESS',
    GET_FORM_ERROR: 'GET_FORM_ERROR',
    POST_FORM_REQUEST: 'POST_FORM_REQUEST',
    POST_FORM_SUCCESS: 'POST_FORM_SUCCESS',
    POST_FORM_ERROR: 'POST_FORM_ERROR',

    /**
     * Restaurant
     */
    GET_RESTAURANT_FORM_REQUEST: 'GET_RESTAURANT_FORM_REQUEST',
    GET_RESTAURANT_FORM_SUCCESS: 'GET_RESTAURANT_FORM_SUCCESS',
    GET_RESTAURANT_FORM_ERROR: 'GET_RESTAURANT_FORM_ERROR',

    POST_RESTAURANT_FORM_REQUEST: 'POST_RESTAURANT_FORM_REQUEST',
    POST_RESTAURANT_FORM_SUCCESS: 'POST_RESTAURANT_FORM_SUCCESS',
    POST_RESTAURANT_FORM_ERROR: 'POST_RESTAURANT_FORM_ERROR',

    /**
     * Delivery Method
     */
    GET_DELIVERY_METHOD_FORM_REQUEST: 'GET_DELIVERY_METHOD_FORM_REQUEST',
    GET_DELIVERY_METHOD_FORM_SUCCESS: 'GET_DELIVERY_METHOD_FORM_SUCCESS',
    GET_DELIVERY_METHOD_FORM_ERROR: 'GET_DELIVERY_METHOD_FORM_ERROR',

    POST_DELIVERY_METHOD_FORM_REQUEST: 'POST_DELIVERY_METHOD_FORM_REQUEST',
    POST_DELIVERY_METHOD_FORM_SUCCESS: 'POST_DELIVERY_METHOD_FORM_SUCCESS',
    POST_DELIVERY_METHOD_FORM_ERROR: 'POST_DELIVERY_METHOD_FORM_ERROR',

    /**
     * Payment Method
     */
    GET_PAYMENT_METHOD_FORM_REQUEST: 'GET_PAYMENT_METHOD_FORM_REQUEST',
    GET_PAYMENT_METHOD_FORM_SUCCESS: 'GET_PAYMENT_METHOD_FORM_SUCCESS',
    GET_PAYMENT_METHOD_FORM_ERROR: 'GET_PAYMENT_METHOD_FORM_ERROR',

    POST_PAYMENT_METHOD_FORM_REQUEST: 'POST_PAYMENT_METHOD_FORM_REQUEST',
    POST_PAYMENT_METHOD_FORM_SUCCESS: 'POST_PAYMENT_METHOD_FORM_SUCCESS',
    POST_PAYMENT_METHOD_FORM_ERROR: 'POST_PAYMENT_METHOD_FORM_ERROR',

    /**
     * Menu
     */
    GET_CATEGORY_LIST_REQUEST: 'GET_CATEGORY_LIST_REQUEST',
    GET_CATEGORY_LIST_SUCCESS: 'GET_CATEGORY_LIST_SUCCESS',
    GET_CATEGORY_LIST_ERROR: 'GET_CATEGORY_LIST_ERROR',

    POST_CATEGORY_FORM_REQUEST: 'POST_CATEGORY_FORM_REQUEST',
    POST_CATEGORY_FORM_SUCCESS: 'POST_CATEGORY_FORM_SUCCESS',
    POST_CATEGORY_FORM_ERROR: 'POST_CATEGORY_FORM_ERROR',

    GET_MENU_LIST_REQUEST: 'GET_MENU_LIST_REQUEST',
    GET_MENU_LIST_SUCCESS: 'GET_MENU_LIST_SUCCESS',
    GET_MENU_LIST_ERROR: 'GET_MENU_LIST_ERROR',

    POST_MENU_FORM_REQUEST: 'POST_MENU_FORM_REQUEST',
    POST_MENU_FORM_SUCCESS: 'POST_MENU_FORM_SUCCESS',
    POST_MENU_FORM_ERROR: 'POST_MENU_FORM_ERROR',
    //  * Control Center
    //  */
    GET_CONTROL_CENTER_METHOD_FORM_REQUEST: 'GET_CONTROL_CENTER_METHOD_FORM_REQUEST',
    GET_CONTROL_CENTER_METHOD_FORM_SUCCESS: 'GET_CONTROL_CENTER_METHOD_FORM_SUCCESS',
    GET_CONTROL_CENTER_METHOD_FORM_ERROR: 'GET_CONTROL_CENTER_METHOD_FORM_ERROR',

    /**
     * Default config
     */
    GET_DEFAULT_CONFIG_REQUEST: 'GET_DEFAULT_CONFIG_REQUEST',
    GET_DEFAULT_CONFIG_SUCCESS: 'GET_DEFAULT_CONFIG_SUCCESS',
    GET_DEFAULT_CONFIG_ERROR: 'GET_DEFAULT_CONFIG_ERROR',

}