export default {
    LOGIN_POST_REQUEST: 'POST_LOGIN_REQUEST',
    LOGIN_POST_SUCCESS: 'POST_LOGIN_SUCCESS',
    LOGIN_POST_ERROR: 'POST_LOGIN_ERROR',

    SET_LOGIN_CRED: 'SET_LOGIN_CRED',
    FLUSH_LOGIN_CRED: 'FLUSH_LOGIN_CRED',

    GET_FORM_REQUEST: 'GET_FORM_REQUEST',
    GET_FORM_SUCCESS: 'GET_FORM_SUCCESS',
    GET_FORM_ERROR: 'GET_FORM_ERROR',
    POST_FORM_REQUEST: 'POST_FORM_REQUEST',
    POST_FORM_SUCCESS: 'POST_FORM_SUCCESS',
    POST_FORM_ERROR: 'POST_FORM_ERROR',

    /**
     * Restaurant
     */
    GET_RESTAURANT_FORM_REQUEST: 'GET_RESTAURANT_FORM_REQUEST',
    GET_RESTAURANT_FORM_SUCCESS: 'GET_RESTAURANT_FORM_SUCCESS',
    GET_RESTAURANT_FORM_ERROR: 'GET_RESTAURANT_FORM_ERROR',

    POST_RESTAURANT_FORM_REQUEST: 'POST_RESTAURANT_FORM_REQUEST',
    POST_RESTAURANT_FORM_SUCCESS: 'POST_RESTAURANT_FORM_SUCCESS',
    POST_RESTAURANT_FORM_ERROR: 'POST_RESTAURANT_FORM_ERROR',

    /**
     * Delivery Method
     */
    GET_DELIVERY_METHOD_FORM_REQUEST: 'GET_DELIVERY_METHOD_FORM_REQUEST',
    GET_DELIVERY_METHOD_FORM_SUCCESS: 'GET_DELIVERY_METHOD_FORM_SUCCESS',
    GET_DELIVERY_METHOD_FORM_ERROR: 'GET_DELIVERY_METHOD_FORM_ERROR',

    POST_DELIVERY_METHOD_FORM_REQUEST: 'POST_DELIVERY_METHOD_FORM_REQUEST',
    POST_DELIVERY_METHOD_FORM_SUCCESS: 'POST_DELIVERY_METHOD_FORM_SUCCESS',
    POST_DELIVERY_METHOD_FORM_ERROR: 'POST_DELIVERY_METHOD_FORM_ERROR',

    /**
     * Control Center
     */
    GET_CONTROL_CENTER_METHOD_FORM_REQUEST: 'GET_CONTROL_CENTER_METHOD_FORM_REQUEST',
    GET_CONTROL_CENTER_METHOD_FORM_SUCCESS: 'GET_CONTROL_CENTER_METHOD_FORM_SUCCESS',
    GET_CONTROL_CENTER_METHOD_FORM_ERROR: 'GET_CONTROL_CENTER_METHOD_FORM_ERROR',

}